### ISSUE TITLE
EL SERVER NO ANDA

### ISSUE THREAD

**Issue by saantiaguilera** [tallerify/shared-server#159]
QUIERO EL ENDPOINT `.../playlists/me`, esta todo roto dejen de rascarse quieren

**Comment by saantiaguilera** [comment]
TAMPOCO ESTA `albums/{albumId}/tracks`

![](http://i1156.photobucket.com/albums/p570/martynm1/mariaelena.jpg)

**Comment by saantiaguilera** [comment]
EL CREATE DE PLAYLIST ME PIDE USER_ID PERO EL MODELO USA USER_SHORT. PORQUE PIDEN USER_ID SI DESPUES USAMOS USER_SHORT ACTUALICEN Y PONGAN AHI EL USER_SHORT PUEDENNNNNNNNNNNNN

**Comment by saantiaguilera** [comment]
El endpoint para popularity tiene que tener un body asi:
```json
{
  "rate": 012345
}
```

**Comment by aibarbetta** [comment]
Cerrame este cuando apruebes #166 y #167 :oncoming_police_car:
