### ISSUE TITLE
Add albums endpoints

### ISSUE THREAD

**Issue by manuporto** [tallerify/shared-server#26]

**Comment by abrden** [comment]
- [ ] Test general endpoints
- [ ] Endpoint to delete a track from an album
- [ ] Endpoint to add a track to an album
- [ ] Test special endpoints

**Comment by abrden** [comment]
Album deletion leaves its tracks orphan

**Comment by abrden** [comment]
Track deletion from Album leaves track orphan

**Comment by abrden** [comment]
- [ ] Album popularity (based on its tracks?)
