### ISSUE TITLE
Endpoints de GET para songs mal documentados

### ISSUE THREAD

**Issue by saantiaguilera** [tallerify/shared-server#59]
Estan mal documentados en ese Rebilly. Que devuelvan `Song` y no `SongShort` al hacer un get a las song de una playlist/album/artist 

Esta relacionado con https://github.com/tallerify/tallerify-catalog/issues/58

**Comment by aibarbetta** [comment]
- [x] `GET api/albums/{albumId}/tracks`
- [x] `GET api/playlists/{albumId}/tracks`
- [x] `GET api/artists/{albumId}/tracks`
