### ISSUE TITLE
Trending endpoints

### ISSUE THREAD

**Issue by saantiaguilera** [tallerify/shared-server#61]
Talves los agreguen despues, por las dudas marco los que faltan al dia de hoy
- [ ] Trending artists (artists/trending?) -> Lo hice sin auth, si llega a necesitar auth avisen!
- [ ] Trending songs (songs/trending?) -> Lo hice sin auth, si llega a necesitar auth avisen!
~~- [ ] Playlists de un user (me/playlists?)~~
- [x] Follow/Unfollow user (users/{id}/follow POST/DELETE?) -> Tampoco sabemos si es doble relacion o simple, si es doble aca se cambiaria por algun request/accept/decline ?

**Comment by aibarbetta** [comment]
Se pueden hacer para que devuelvan n tracks/artists/albums más populares

**Comment by saantiaguilera** [comment]
Negativo, no va a pasar
