### ISSUE TITLE
Cambios en el pedido de follow / unfollow users

### ISSUE THREAD

**Issue by saantiaguilera** [tallerify/shared-server#90]
Los tenia como

POST/DELETE a: users/{my_id}/follow
Body: 
```Json
{
  "userId": "user_to_follow/unfollow_id"
}
```

Dado que ya es authenticated, podemos sacar el body y que sea la url
`users/{user_to_follow/unfollow_id}/follow` ? De esta forma no mandariamos mi id ya que lo obtienen del token

Porque el cliente nativo de android no permite Deletes con body (es un bug de ellos, esta fileado)

Yapa: Asi como propongo estan los follow/unfollow a artistas y canciones en la docu, supongo que les quedo mal en estos endpoints justo jaja

**Comment by abrden** [comment]
En la doc no figuran pero, según el enunciado, agregar un amigo se hace con `POST /api/users/me/contacts/{idDelAmigo}`. El de borrar no lo menciona pero lo invente como `DELETE /api/users/me/contacts/{idDelAmigo}`. 
Ambos sin body, te sirven?
