### ISSUE TITLE
Save facebook's userId and authToken on users table

### ISSUE THREAD

**Issue by abrden** [tallerify/shared-server#96]
And add **fb** field to `api/users` responses when possible
[api doc](http://rebilly.github.io/ReDoc/?url=https://gist.githubusercontent.com/NickCis/24b3922f204af2f44d85fae927fc6dc5/raw/975b713824b728a85d80a9ab1c11c5b7f367faf8/music-shared-api.yaml#section/Authentication)

**Comment by manuporto** [comment]
Solved in #97
